import { useCallback, useEffect, useRef } from 'react';
import type { AutomationSettings } from './useAutomationSettings';

interface UseAutomationFlowProps {
  // Automation settings
  automationSettings: AutomationSettings;
  isAutomationLoading: boolean;

  // OCR state
  ocrText: string;
  optimizedText: string;
  isOptimizingText: boolean;
  isOptimizing: boolean;

  // Generation state
  optimizedPrompt: string;
  isGenerating: boolean;
  generatedImageUrl: string;

  // Session state
  isRestoringSession: boolean;

  // Callbacks
  optimizeOcrText: () => Promise<void>;
  optimizePrompt: () => Promise<void>;
  triggerImageGeneration: (prompt: string) => boolean;
  saveGeneratedImageToDirectory: (directory: string) => Promise<string | undefined>;
}

export const useAutomationFlow = (props: UseAutomationFlowProps) => {
  const {
    automationSettings,
    isAutomationLoading,
    ocrText,
    optimizedText,
    isOptimizingText,
    isOptimizing,
    optimizedPrompt,
    isGenerating,
    generatedImageUrl,
    isRestoringSession,
    optimizeOcrText,
    optimizePrompt,
    triggerImageGeneration,
    saveGeneratedImageToDirectory
  } = props;

  // Refs to track what has been auto-processed to prevent duplicates
  const lastAutoOptimizedOcrRef = useRef<string>('');
  const lastAutoPromptRef = useRef<string>('');
  const lastAutoGeneratedImageRef = useRef<string>('');
  const lastAutoSavedImageRef = useRef<string>('');
  const automationSettingsRef = useRef(automationSettings);

  // Keep automation settings ref in sync
  useEffect(() => {
    automationSettingsRef.current = automationSettings;
  }, [automationSettings]);

  // Reset automation tracking for new image
  const resetAutomationTracking = useCallback(() => {
    lastAutoOptimizedOcrRef.current = '';
    lastAutoPromptRef.current = '';
    lastAutoGeneratedImageRef.current = '';
    lastAutoSavedImageRef.current = '';
  }, []);

  // Reset specific automation tracking (used when session is restored)
  const resetConditionalTracking = useCallback((ocrText: string, optimizedText: string, optimizedPrompt: string) => {
    if (ocrText && !optimizedText) {
      lastAutoOptimizedOcrRef.current = '';
    }
    if (ocrText && !optimizedPrompt) {
      lastAutoPromptRef.current = '';
    }
  }, []);

  // Check if auto-optimization should trigger after OCR completion
  const shouldAutoOptimizeOcr = useCallback((sessionId: string, activeSessionId: string | null, ocrText: string) => {
    const settings = automationSettingsRef.current;
    if (sessionId !== activeSessionId) return false;
    if (!settings.autoOptimizeOcr) return false;
    if (!ocrText.trim()) return false;
    if (isRestoringSession) return false;
    return true;
  }, [isRestoringSession]);

  // Mark OCR as auto-optimized
  const markOcrAsAutoOptimized = useCallback((ocrText: string) => {
    lastAutoOptimizedOcrRef.current = ocrText;
  }, []);

  // Check if auto-prompt generation should trigger after OCR completion
  const shouldAutoGeneratePromptAfterOcr = useCallback((sessionId: string, activeSessionId: string | null, ocrText: string) => {
    const settings = automationSettingsRef.current;
    if (sessionId !== activeSessionId) return false;
    if (!settings.autoGeneratePrompt) return false;
    if (!ocrText.trim()) return false;
    if (isRestoringSession) return false;
    return true;
  }, [isRestoringSession]);

  // Reset prompt tracking to allow auto-generation
  const resetPromptTracking = useCallback(() => {
    lastAutoPromptRef.current = '';
  }, []);

  // Trigger image generation with tracking
  const triggerImageGenerationWithTracking = useCallback((prompt: string) => {
    if (triggerImageGeneration(prompt)) {
      lastAutoGeneratedImageRef.current = prompt;
      return true;
    }
    return false;
  }, [triggerImageGeneration]);

  // Auto-optimize when setting is enabled and OCR text exists without optimization
  // This works in conjunction with handleOcrComplete to support two scenarios:
  // 1. Auto-optimize on OCR completion (handled in handleOcrComplete)
  // 2. Auto-optimize when user enables the setting after OCR is complete (handled here)
  useEffect(() => {
    if (isAutomationLoading) {
      return;
    }

    if (!automationSettings.autoOptimizeOcr || !ocrText.trim() || isRestoringSession || isOptimizingText) {
      return;
    }

    // Only auto-optimize if there's no optimized text yet
    // This prevents duplicate optimization when handleOcrComplete already optimized
    if (optimizedText.trim()) {
      return;
    }

    if (lastAutoOptimizedOcrRef.current === ocrText) {
      return;
    }

    lastAutoOptimizedOcrRef.current = ocrText;
    void optimizeOcrText();
  }, [automationSettings.autoOptimizeOcr, isAutomationLoading, isOptimizingText, isRestoringSession, ocrText, optimizedText, optimizeOcrText]);

  // Auto-generate prompt when OCR text changes
  useEffect(() => {
    if (isAutomationLoading) {
      return;
    }

    if (!automationSettings.autoGeneratePrompt || !ocrText.trim() || isRestoringSession || isOptimizing) {
      return;
    }

    if (lastAutoPromptRef.current === ocrText) {
      return;
    }

    lastAutoPromptRef.current = ocrText;
    void optimizePrompt();
  }, [automationSettings.autoGeneratePrompt, isAutomationLoading, isOptimizing, isRestoringSession, ocrText, optimizePrompt]);

  // Auto-generate image when prompt is ready
  useEffect(() => {
    if (isAutomationLoading) {
      return;
    }

    if (!automationSettings.autoGenerateImage || !optimizedPrompt.trim() || isRestoringSession || isGenerating) {
      return;
    }

    if (lastAutoGeneratedImageRef.current === optimizedPrompt) {
      return;
    }

    if (triggerImageGeneration(optimizedPrompt)) {
      lastAutoGeneratedImageRef.current = optimizedPrompt;
    }
  }, [automationSettings.autoGenerateImage, isAutomationLoading, isGenerating, isRestoringSession, optimizedPrompt, triggerImageGeneration]);

  // Auto-save generated image
  useEffect(() => {
    if (isAutomationLoading) {
      return;
    }

    if (!automationSettings.autoSaveImage ||
        !automationSettings.autoSaveDirectory.trim() ||
        !generatedImageUrl ||
        isRestoringSession) {
      return;
    }

    if (lastAutoSavedImageRef.current === generatedImageUrl) {
      return;
    }

    lastAutoSavedImageRef.current = generatedImageUrl;
    void saveGeneratedImageToDirectory(automationSettings.autoSaveDirectory).catch(() => {
      // Error already surfaced via generation status; no-op here.
    });
  }, [
    automationSettings.autoSaveDirectory,
    automationSettings.autoSaveImage,
    generatedImageUrl,
    isAutomationLoading,
    isRestoringSession,
    saveGeneratedImageToDirectory
  ]);

  return {
    // Refs for external use
    automationSettingsRef,

    // Methods for managing automation tracking
    resetAutomationTracking,
    resetConditionalTracking,
    shouldAutoOptimizeOcr,
    markOcrAsAutoOptimized,
    shouldAutoGeneratePromptAfterOcr,
    resetPromptTracking,
    triggerImageGenerationWithTracking
  };
};
