import React, { createContext, useContext, useRef, useEffect } from 'react';
import { useAutomationSettings } from '../hooks/useAutomationSettings';
import type { AutomationSettings } from '../hooks/useAutomationSettings';

interface AutomationContextValue {
  // Settings
  settings: AutomationSettings;
  isLoading: boolean;

  // Actions
  updateSetting: (key: keyof AutomationSettings, value: boolean | string) => void;

  // Control flags (refs to avoid stale closures)
  suppressAutoProcessRef: React.MutableRefObject<boolean>;
  suppressPromptResetRef: React.MutableRefObject<boolean>;
  isRestoringSessionRef: React.MutableRefObject<boolean>;

  // Tracking refs (prevent duplicate automation)
  lastAutoOptimizedOcrRef: React.MutableRefObject<string>;
  lastAutoPromptRef: React.MutableRefObject<string>;
  lastAutoGeneratedImageRef: React.MutableRefObject<string>;
  lastAutoSavedImageRef: React.MutableRefObject<string>;

  // Helper ref for latest settings
  settingsRef: React.MutableRefObject<AutomationSettings>;
}

const AutomationContext = createContext<AutomationContextValue | null>(null);

export const useAutomationContext = () => {
  const context = useContext(AutomationContext);
  if (!context) {
    throw new Error('useAutomationContext must be used within AutomationProvider');
  }
  return context;
};

export const AutomationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const {
    settings,
    updateSetting,
    isLoading
  } = useAutomationSettings();

  // Control flags
  const suppressAutoProcessRef = useRef<boolean>(false);
  const suppressPromptResetRef = useRef<boolean>(false);
  const isRestoringSessionRef = useRef<boolean>(false);

  // Tracking refs
  const lastAutoOptimizedOcrRef = useRef<string>('');
  const lastAutoPromptRef = useRef<string>('');
  const lastAutoGeneratedImageRef = useRef<string>('');
  const lastAutoSavedImageRef = useRef<string>('');

  // Settings ref for avoiding stale closures
  const settingsRef = useRef(settings);

  useEffect(() => {
    settingsRef.current = settings;
  }, [settings]);

  const value: AutomationContextValue = {
    settings,
    isLoading,
    updateSetting,
    suppressAutoProcessRef,
    suppressPromptResetRef,
    isRestoringSessionRef,
    lastAutoOptimizedOcrRef,
    lastAutoPromptRef,
    lastAutoGeneratedImageRef,
    lastAutoSavedImageRef,
    settingsRef
  };

  return (
    <AutomationContext.Provider value={value}>
      {children}
    </AutomationContext.Provider>
  );
};
